name: sample
on:
    push:
        branches: [ branch1 ]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v3
        -   name: Setup python 3.8
            uses: actions/setup-python@v2
            with:
                python-version: 3.8
        